# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-01-26 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.TextField()),
                ('date', models.DateField(verbose_name='date pasted')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('display_name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastebin.User'),
        ),
    ]
