# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-01-28 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.TextField()),
                ('creation_date', models.DateField(verbose_name='date pasted')),
                ('expiry_date', models.DateField(verbose_name='date pasted')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastebin.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='text',
            name='user',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
