# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-01-28 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0002_auto_20170128_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='paste',
            name='hash',
            field=models.CharField(default='undefined', max_length=20),
        ),
        migrations.AlterField(
            model_name='paste',
            name='creation_date',
            field=models.DateField(verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='expiry_date',
            field=models.DateField(verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='paste',
            name='expiration_enum',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='pastebin.Duration'),
        ),
    ]
