# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-01-28 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0003_auto_20170128_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='duration',
            name='addition_minutes',
            field=models.BigIntegerField(default=15),
        ),
    ]
