# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-01-29 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0004_duration_addition_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paste',
            old_name='expiration_enum',
            new_name='expiration',
        ),
        migrations.AddField(
            model_name='duration',
            name='description',
            field=models.CharField(default='undefined', max_length=100),
        ),
    ]
