# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-01-29 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0005_auto_20170129_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='expiry_date',
            field=models.DateTimeField(verbose_name='expiration date'),
        ),
    ]
