# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-01-29 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0006_auto_20170129_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='expiration',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='pastebin.Duration'),
        ),
    ]
