# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-18 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0009_auto_20170217_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPasteStats',
            new_name='UserExtraInfo',
        ),
    ]
